-- EstateKit production database: structure snapshot
--
-- Taken 2026-09-25T07:03:27.843Z from project yfcnsvrhojpysrzqrkdi, read-only,
-- via `supabase db query --linked` against the Postgres catalog (pg_dump needs
-- Docker, which isn't installed). Generated by a query, not typed by hand.
--
-- WHAT THIS IS FOR
--   Disaster recovery and change review. Most of this structure was created by
--   clicking in the Supabase dashboard and existed nowhere else. Diff future
--   snapshots against this one to see exactly what changed.
--
-- WHAT THIS IS NOT
--   Not a migration. It lives outside supabase/migrations on purpose so nothing
--   ever runs it against production. It creates objects without IF NOT EXISTS
--   guards on constraints and policies, so it only applies cleanly to an EMPTY
--   project, in file order.
--
-- NOT INCLUDED
--   Data. Vault secrets. Edge function secrets. Auth settings (dashboard).
--   Objects in the auth / storage schemas other than storage policies, storage
--   buckets and triggers that call a public function.
--
-- Counts: Extensions 6, Tables 24, Primary keys, unique and check constraints 46, Foreign keys 22, Indexes 30, Functions 10, Function privileges 10, Triggers 7, Row level security 24, Policies (public + storage) 66, Table privileges (anon / authenticated) 24, Storage buckets 1, Cron jobs 3, Comments 5
--
-- Redacted secrets: none found

-- ==========================================================================
-- 1. Extensions
-- ==========================================================================

create extension if not exists pg_cron with schema pg_catalog;

create extension if not exists pg_net with schema extensions;

create extension if not exists pg_stat_statements with schema extensions;

create extension if not exists pgcrypto with schema extensions;

create extension if not exists supabase_vault with schema vault;

create extension if not exists "uuid-ossp" with schema extensions;


-- ==========================================================================
-- 4. Tables
-- ==========================================================================

create table if not exists public.agent_daily_nudges (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  sent_on date not null,
  lead_count integer default 0 not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.agent_profiles (
  agent_id uuid not null,
  display_name text,
  whatsapp_number text,
  updated_at timestamp with time zone default now() not null,
  is_operator boolean default false not null,
  tier text default 'paid'::text not null,
  email text default ''::text not null,
  area text default ''::text not null,
  company text default ''::text not null,
  contract_pdf_url text,
  renewal_date date,
  adspend_balance numeric default 0 not null,
  billing_type text default 'prepaid'::text not null,
  fb_ad_account_id text default ''::text,
  fb_page_id text default ''::text,
  sidebar_color text default '#111827'::text,
  sidebar_logo_url text,
  onboarded boolean default false not null,
  automations_paused boolean default false not null,
  avatar_url text
);

create table if not exists public.automation_runs (
  id uuid default gen_random_uuid() not null,
  lead_id uuid not null,
  automation_id uuid not null,
  current_step integer default 0 not null,
  run_at timestamp with time zone not null,
  status text default 'pending'::text not null,
  created_at timestamp with time zone default now() not null,
  template_override text
);

create table if not exists public.automation_steps (
  id uuid default gen_random_uuid() not null,
  automation_id uuid not null,
  step_order integer not null,
  delay_minutes integer default 0 not null,
  action_type text not null,
  template_text text,
  payload jsonb default '{}'::jsonb not null
);

create table if not exists public.automations (
  id uuid default gen_random_uuid() not null,
  name text not null,
  trigger_type text not null,
  trigger_stage text,
  enabled boolean default true not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.call_questions (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  question text not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.custom_questions (
  id uuid default gen_random_uuid() not null,
  page_id uuid not null,
  agent_id uuid not null,
  label text not null,
  type text not null,
  options jsonb default '[]'::jsonb,
  helper_text text,
  required boolean default false not null,
  is_default boolean default false not null,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  disqualify_answers text[] default '{}'::text[] not null,
  low_quality_answers text[] default '{}'::text[] not null
);

create table if not exists public.fb_api_state (
  id boolean default true not null,
  backoff_until timestamp with time zone,
  last_error text,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fb_capi_config (
  pixel_id text not null,
  access_token text not null,
  enabled boolean default false not null,
  test_event_code text,
  label text default ''::text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.fb_capi_events (
  id uuid default gen_random_uuid() not null,
  lead_id uuid,
  pixel_id text not null,
  event_id text not null,
  event_name text not null,
  status text not null,
  response text,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.fb_form_cache (
  form_id text not null,
  page_id text,
  payload jsonb not null,
  fetched_at timestamp with time zone default now() not null
);

create table if not exists public.fb_page_tokens (
  page_id text not null,
  access_token text not null,
  source_secret text default ''::text not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.lead_events (
  id uuid default gen_random_uuid() not null,
  lead_id uuid not null,
  agent_id uuid,
  actor_id uuid,
  event_type text not null,
  from_value text,
  to_value text,
  source text default 'system'::text not null,
  created_at timestamp with time zone default now() not null,
  device text
);

create table if not exists public.lead_page_events (
  id uuid default gen_random_uuid() not null,
  page_id uuid not null,
  agent_id uuid not null,
  session_id text not null,
  event_type text not null,
  source text,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.lead_pages (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  pipeline_id uuid not null,
  name text not null,
  agent_name text default ''::text not null,
  headline text default ''::text not null,
  suburb text default ''::text not null,
  phone text default ''::text not null,
  logo_data_url text,
  profile_photo_data_url text,
  accent_color text default '#1976d2'::text not null,
  show_intro boolean default true not null,
  name_label text default 'What''s your name?'::text not null,
  phone_label text default 'WhatsApp number'::text not null,
  cta_label text default 'Get my free estimate'::text not null,
  thank_you_headline text default 'Thanks {name}! We''ll call you shortly.'::text not null,
  thank_you_subtext text default 'One of our agents will be in touch within the hour.'::text not null,
  fb_pixel_id text default ''::text not null,
  created_at timestamp with time zone default now() not null,
  slug text not null,
  source_type text default 'website'::text,
  fb_form_id text,
  fb_form_name text,
  collect_email boolean default true not null,
  fb_page_id text
);

create table if not exists public.lead_share_tokens (
  id uuid default gen_random_uuid() not null,
  lead_id uuid not null,
  agent_id uuid not null,
  token text not null,
  link_type text default 'first_touch'::text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.leads (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  name text not null,
  phone text not null,
  email text,
  stage text default 'New Lead'::text not null,
  next_label text default 'Just came in'::text not null,
  reminder_at timestamp with time zone,
  due boolean default true not null,
  form_answers jsonb default '[]'::jsonb not null,
  note text default ''::text not null,
  commission integer,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  pipeline_id uuid,
  source_page_id uuid,
  fb_lead_id text,
  archived boolean default false not null,
  fb_ad_id text,
  attribution jsonb default '{}'::jsonb not null,
  quality text default 'good'::text not null,
  commission_received_at timestamp with time zone
);

create table if not exists public.otp_codes (
  id uuid default gen_random_uuid() not null,
  phone text not null,
  code text not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.overview_daily (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  date date not null,
  spend numeric default 0 not null,
  leads integer default 0 not null,
  appts integer default 0 not null,
  mandates integer default 0 not null,
  commission numeric default 0 not null,
  leads_reached integer default 0 not null,
  appts_held integer default 0 not null,
  commission_expected numeric default 0 not null,
  commission_earned numeric default 0 not null
);

create table if not exists public.phone_otp_codes (
  id uuid default gen_random_uuid() not null,
  phone text not null,
  code_hash text not null,
  expires_at timestamp with time zone not null,
  attempts integer default 0 not null,
  consumed boolean default false not null,
  created_at timestamp with time zone default now() not null
);

create table if not exists public.pipelines (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  name text not null,
  kind text not null,
  created_at timestamp with time zone default now() not null,
  sheet_url text
);

create table if not exists public.setup_steps (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  key text not null,
  title text not null,
  sort_order integer not null,
  done boolean default false not null,
  cta_label text,
  cta_url text,
  cta_filled boolean default false not null
);

create table if not exists public.sold_listings (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  image_url text,
  address text default ''::text not null,
  price bigint,
  sort_order integer default 0 not null,
  created_at timestamp with time zone default now() not null,
  status text default 'sold'::text not null
);

create table if not exists public.support_tickets (
  id uuid default gen_random_uuid() not null,
  agent_id uuid not null,
  type text not null,
  priority text not null,
  message text not null,
  emailed boolean default false not null,
  created_at timestamp with time zone default now() not null
);


-- ==========================================================================
-- 5. Primary keys, unique and check constraints
-- ==========================================================================

alter table agent_daily_nudges add constraint agent_daily_nudges_agent_id_sent_on_key UNIQUE (agent_id, sent_on);

alter table agent_daily_nudges add constraint agent_daily_nudges_pkey PRIMARY KEY (id);

alter table agent_profiles add constraint agent_profiles_billing_type_check CHECK ((billing_type = ANY (ARRAY['card'::text, 'prepaid'::text])));

alter table agent_profiles add constraint agent_profiles_pkey PRIMARY KEY (agent_id);

alter table agent_profiles add constraint agent_profiles_tier_check CHECK ((tier = ANY (ARRAY['free'::text, 'paid'::text])));

alter table automation_runs add constraint automation_runs_pkey PRIMARY KEY (id);

alter table automation_runs add constraint automation_runs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'cancelled'::text, 'paused'::text])));

alter table automation_steps add constraint automation_steps_action_type_check CHECK ((action_type = ANY (ARRAY['send_whatsapp'::text, 'set_reminder'::text, 'set_stage'::text])));

alter table automation_steps add constraint automation_steps_automation_id_step_order_key UNIQUE (automation_id, step_order);

alter table automation_steps add constraint automation_steps_pkey PRIMARY KEY (id);

alter table automations add constraint automations_pkey PRIMARY KEY (id);

alter table automations add constraint automations_trigger_stage_check CHECK (((trigger_stage IS NULL) OR (trigger_stage = ANY (ARRAY['New Lead'::text, 'No Answer'::text, 'Contacted'::text, 'Booked'::text, 'Mandate Signed'::text, 'Viewing Booked'::text, 'Offer Made'::text, 'Bought'::text, 'Lost'::text, 'Invalid Number'::text]))));

alter table automations add constraint automations_trigger_type_check CHECK ((trigger_type = ANY (ARRAY['stage_changed'::text, 'reminder_due'::text, 'lead_created'::text, 'daily_digest'::text])));

alter table call_questions add constraint call_questions_pkey PRIMARY KEY (id);

alter table custom_questions add constraint custom_questions_pkey PRIMARY KEY (id);

alter table custom_questions add constraint custom_questions_type_check CHECK ((type = ANY (ARRAY['short_text'::text, 'address'::text, 'multiple_choice'::text, 'yes_no'::text])));

alter table fb_api_state add constraint fb_api_state_pkey PRIMARY KEY (id);

alter table fb_api_state add constraint fb_api_state_single_row CHECK (id);

alter table fb_capi_config add constraint fb_capi_config_pkey PRIMARY KEY (pixel_id);

alter table fb_capi_events add constraint fb_capi_events_event_id_key UNIQUE (event_id);

alter table fb_capi_events add constraint fb_capi_events_pkey PRIMARY KEY (id);

alter table fb_form_cache add constraint fb_form_cache_pkey PRIMARY KEY (form_id);

alter table fb_page_tokens add constraint fb_page_tokens_pkey PRIMARY KEY (page_id);

alter table lead_events add constraint lead_events_event_type_check CHECK ((event_type = ANY (ARRAY['created'::text, 'stage_changed'::text, 'note_changed'::text, 'archived'::text, 'restored'::text, 'pipeline_moved'::text, 'call'::text, 'whatsapp_sent'::text])));

alter table lead_events add constraint lead_events_pkey PRIMARY KEY (id);

alter table lead_page_events add constraint lead_page_events_event_type_check CHECK ((event_type = ANY (ARRAY['view'::text, 'start'::text, 'contact'::text, 'disqualified'::text, 'submit'::text])));

alter table lead_page_events add constraint lead_page_events_pkey PRIMARY KEY (id);

alter table lead_pages add constraint lead_pages_pkey PRIMARY KEY (id);

alter table lead_pages add constraint lead_pages_slug_key UNIQUE (slug);

alter table lead_share_tokens add constraint lead_share_tokens_link_type_check CHECK ((link_type = ANY (ARRAY['first_touch'::text, 'retry_nudge'::text, 'snooze_followup'::text, 'post_appointment'::text])));

alter table lead_share_tokens add constraint lead_share_tokens_pkey PRIMARY KEY (id);

alter table lead_share_tokens add constraint lead_share_tokens_token_key UNIQUE (token);

alter table leads add constraint leads_pkey PRIMARY KEY (id);

alter table leads add constraint leads_quality_check CHECK ((quality = ANY (ARRAY['good'::text, 'weak'::text])));

alter table leads add constraint leads_stage_check CHECK ((stage = ANY (ARRAY['New Lead'::text, 'No Answer'::text, 'Contacted'::text, 'Booked'::text, 'Mandate Signed'::text, 'Viewing Booked'::text, 'Offer Made'::text, 'Bought'::text, 'Lost'::text, 'Invalid Number'::text])));

alter table otp_codes add constraint otp_codes_pkey PRIMARY KEY (id);

alter table overview_daily add constraint overview_daily_agent_id_date_key UNIQUE (agent_id, date);

alter table overview_daily add constraint overview_daily_pkey PRIMARY KEY (id);

alter table phone_otp_codes add constraint phone_otp_codes_pkey PRIMARY KEY (id);

alter table pipelines add constraint pipelines_kind_check CHECK ((kind = ANY (ARRAY['seller'::text, 'buyer'::text, 'general'::text])));

alter table pipelines add constraint pipelines_pkey PRIMARY KEY (id);

alter table setup_steps add constraint setup_steps_agent_id_key_key UNIQUE (agent_id, key);

alter table setup_steps add constraint setup_steps_pkey PRIMARY KEY (id);

alter table sold_listings add constraint sold_listings_pkey PRIMARY KEY (id);

alter table sold_listings add constraint sold_listings_status_check CHECK ((status = ANY (ARRAY['sold'::text, 'listed'::text])));

alter table support_tickets add constraint support_tickets_pkey PRIMARY KEY (id);


-- ==========================================================================
-- 6. Foreign keys
-- ==========================================================================

alter table agent_daily_nudges add constraint agent_daily_nudges_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table agent_profiles add constraint agent_profiles_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table automation_runs add constraint automation_runs_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES automations(id) ON DELETE CASCADE;

alter table automation_runs add constraint automation_runs_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;

alter table automation_steps add constraint automation_steps_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES automations(id) ON DELETE CASCADE;

alter table call_questions add constraint call_questions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table custom_questions add constraint custom_questions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id);

alter table custom_questions add constraint custom_questions_page_id_fkey FOREIGN KEY (page_id) REFERENCES lead_pages(id) ON DELETE CASCADE;

alter table fb_capi_events add constraint fb_capi_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL;

alter table lead_events add constraint lead_events_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;

alter table lead_page_events add constraint lead_page_events_page_id_fkey FOREIGN KEY (page_id) REFERENCES lead_pages(id) ON DELETE CASCADE;

alter table lead_pages add constraint lead_pages_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id);

alter table lead_pages add constraint lead_pages_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES pipelines(id);

alter table lead_share_tokens add constraint lead_share_tokens_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id);

alter table lead_share_tokens add constraint lead_share_tokens_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE;

alter table leads add constraint leads_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table leads add constraint leads_pipeline_id_fkey FOREIGN KEY (pipeline_id) REFERENCES pipelines(id);

alter table overview_daily add constraint overview_daily_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table pipelines add constraint pipelines_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id);

alter table setup_steps add constraint setup_steps_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table sold_listings add constraint sold_listings_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;

alter table support_tickets add constraint support_tickets_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id) ON DELETE CASCADE;


-- ==========================================================================
-- 7. Indexes
-- ==========================================================================

CREATE INDEX agent_daily_nudges_sent_on_idx ON public.agent_daily_nudges USING btree (sent_on DESC);

CREATE UNIQUE INDEX automation_runs_active_unique ON public.automation_runs USING btree (lead_id, automation_id) WHERE (status = ANY (ARRAY['pending'::text, 'processing'::text, 'paused'::text]));

CREATE INDEX automation_runs_due_idx ON public.automation_runs USING btree (run_at) WHERE (status = 'pending'::text);

CREATE INDEX automation_runs_lead_idx ON public.automation_runs USING btree (lead_id);

CREATE INDEX automation_steps_automation_idx ON public.automation_steps USING btree (automation_id, step_order);

CREATE INDEX call_questions_agent_idx ON public.call_questions USING btree (agent_id);

CREATE INDEX fb_capi_events_created_idx ON public.fb_capi_events USING btree (created_at DESC);

CREATE INDEX fb_capi_events_lead_idx ON public.fb_capi_events USING btree (lead_id);

CREATE INDEX idx_custom_questions_page ON public.custom_questions USING btree (page_id, sort_order);

CREATE INDEX idx_lead_share_tokens_lead ON public.lead_share_tokens USING btree (lead_id);

CREATE INDEX idx_lead_share_tokens_token ON public.lead_share_tokens USING btree (token);

CREATE INDEX idx_leads_agent_pipeline ON public.leads USING btree (agent_id, pipeline_id);

CREATE INDEX lead_events_lead_created_idx ON public.lead_events USING btree (lead_id, created_at DESC);

CREATE UNIQUE INDEX lead_page_events_once_per_session ON public.lead_page_events USING btree (page_id, session_id, event_type);

CREATE INDEX lead_page_events_page_created_idx ON public.lead_page_events USING btree (page_id, created_at DESC);

CREATE INDEX lead_pages_fb_page_idx ON public.lead_pages USING btree (fb_page_id) WHERE (fb_page_id IS NOT NULL);

CREATE UNIQUE INDEX lead_pages_slug_idx ON public.lead_pages USING btree (slug);

CREATE INDEX leads_agent_due_idx ON public.leads USING btree (agent_id, due) WHERE due;

CREATE INDEX leads_agent_idx ON public.leads USING btree (agent_id);

CREATE INDEX leads_agent_stage_idx ON public.leads USING btree (agent_id, stage);

CREATE INDEX leads_archived_idx ON public.leads USING btree (agent_id, archived);

CREATE INDEX leads_attribution_ad_id_idx ON public.leads USING btree (((attribution ->> 'ad_id'::text))) WHERE ((attribution ->> 'ad_id'::text) IS NOT NULL);

CREATE INDEX leads_commission_received_idx ON public.leads USING btree (commission_received_at) WHERE (commission_received_at IS NOT NULL);

CREATE UNIQUE INDEX leads_fb_lead_id_key ON public.leads USING btree (fb_lead_id) WHERE (fb_lead_id IS NOT NULL);

CREATE INDEX leads_quality_idx ON public.leads USING btree (quality) WHERE (quality <> 'good'::text);

CREATE INDEX overview_daily_agent_idx ON public.overview_daily USING btree (agent_id, date DESC);

CREATE INDEX phone_otp_codes_phone_idx ON public.phone_otp_codes USING btree (phone, created_at DESC);

CREATE INDEX setup_steps_agent_idx ON public.setup_steps USING btree (agent_id, sort_order);

CREATE INDEX sold_listings_agent_idx ON public.sold_listings USING btree (agent_id, sort_order);

CREATE INDEX support_tickets_agent_idx ON public.support_tickets USING btree (agent_id);


-- ==========================================================================
-- 9. Functions
-- ==========================================================================

CREATE OR REPLACE FUNCTION public.dedupe_lead_call()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.event_type = 'call' and exists (
    select 1 from public.lead_events e
    where e.lead_id = new.lead_id
      and e.event_type = 'call'
      and e.actor_id is not distinct from new.actor_id
      and e.created_at > now() - interval '2 minutes'
  ) then
    return null;
  end if;

  if new.device is null and auth.uid() is not null then
    begin
      new.device := left(nullif(current_setting('request.headers', true), '')::json->>'user-agent', 300);
    exception when others then
      null;
    end;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enqueue_automations()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  auto record;
  step record;
begin
  if tg_op = 'INSERT' then
    if new.created_at >= now() - interval '30 minutes' then
      for auto in
        select id from public.automations
        where trigger_type = 'lead_created' and enabled = true
      loop
        select delay_minutes into step from public.automation_steps
          where automation_id = auto.id and step_order = 0 limit 1;
        insert into public.automation_runs (lead_id, automation_id, current_step, run_at, status)
        values (new.id, auto.id, 0,
          now() + coalesce(step.delay_minutes, 0) * interval '1 minute',
          'pending')
        on conflict (lead_id, automation_id)
          where status = any (array['pending','processing'])
          do nothing;
      end loop;
    end if;
  end if;

  if tg_op = 'UPDATE' and old.stage is distinct from new.stage then
    for auto in
      select id from public.automations
      where trigger_type = 'stage_changed'
        and enabled = true
        and (trigger_stage is null or trigger_stage = new.stage)
    loop
      select delay_minutes into step from public.automation_steps
        where automation_id = auto.id and step_order = 0 limit 1;
      insert into public.automation_runs (lead_id, automation_id, current_step, run_at, status)
      values (new.id, auto.id, 0,
        now() + coalesce(step.delay_minutes, 0) * interval '1 minute',
        'pending')
      on conflict (lead_id, automation_id)
        where status = any (array['pending','processing'])
        do nothing;
    end loop;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.find_user_id_by_phone(p_phone text)
 RETURNS uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
  select id from auth.users where phone = p_phone limit 1;
$function$
;

CREATE OR REPLACE FUNCTION public.get_secret(secret_name text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'vault', 'pg_temp'
AS $function$
DECLARE
  result text;
BEGIN
  SELECT decrypted_secret INTO result
  FROM vault.decrypted_secrets
  WHERE name = secret_name
  LIMIT 1;
  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_operator()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
  SELECT COALESCE((SELECT is_operator FROM agent_profiles WHERE agent_id = auth.uid()), false);
$function$
;

CREATE OR REPLACE FUNCTION public.lead_page_funnel(p_page_id uuid, p_since timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS TABLE(views bigint, starts bigint, contacts bigint, disqualified bigint, submits bigint)
 LANGUAGE sql
 STABLE
 SET search_path TO 'public'
AS $function$
  select
    count(*) filter (where event_type = 'view'),
    count(*) filter (where event_type = 'start'),
    count(*) filter (where event_type = 'contact'),
    count(*) filter (where event_type = 'disqualified'),
    count(*) filter (where event_type = 'submit')
  from public.lead_page_events
  where page_id = p_page_id
    and (p_since is null or created_at >= p_since);
$function$
;

CREATE OR REPLACE FUNCTION public.record_lead_event()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  hdrs json;
  v_actor uuid;
  v_source text := 'system';
  v_device text;
  last_note uuid;
begin
  begin
    hdrs := nullif(current_setting('request.headers', true), '')::json;
  exception when others then
    hdrs := null;
  end;

  if auth.uid() is not null then
    v_actor := auth.uid();
    v_source := 'dashboard';
    v_device := left(hdrs->>'user-agent', 300);
  elsif coalesce(auth.role(), '') = 'service_role' then
    v_source := coalesce(nullif(hdrs->>'x-ek-source', ''), 'system');
    begin
      v_actor := nullif(hdrs->>'x-ek-actor', '')::uuid;
    exception when others then
      v_actor := null;
    end;
    v_device := left(nullif(hdrs->>'x-ek-device', ''), 300);
  end if;

  if tg_op = 'INSERT' then
    insert into public.lead_events (lead_id, agent_id, actor_id, event_type, to_value, source, device, created_at)
    values (
      new.id, new.agent_id, v_actor, 'created', new.stage,
      case
        when new.fb_lead_id is not null then 'facebook'
        when new.source_page_id is not null then 'website'
        else v_source
      end,
      v_device,
      coalesce(new.created_at, now())
    );
    return new;
  end if;

  if new.stage is distinct from old.stage then
    insert into public.lead_events (lead_id, agent_id, actor_id, event_type, from_value, to_value, source, device)
    values (new.id, new.agent_id, v_actor, 'stage_changed', old.stage, new.stage, v_source, v_device);
  end if;

  if new.pipeline_id is distinct from old.pipeline_id then
    insert into public.lead_events (lead_id, agent_id, actor_id, event_type, from_value, to_value, source, device)
    values (
      new.id, new.agent_id, v_actor, 'pipeline_moved',
      (select name from public.pipelines where id = old.pipeline_id),
      (select name from public.pipelines where id = new.pipeline_id),
      v_source, v_device
    );
  end if;

  if new.archived is distinct from old.archived then
    insert into public.lead_events (lead_id, agent_id, actor_id, event_type, source, device)
    values (new.id, new.agent_id, v_actor, case when new.archived then 'archived' else 'restored' end, v_source, v_device);
  end if;

  -- Notes autosave as you type, so fold edits by the same person within 10
  -- minutes into one entry instead of one per keystroke burst.
  if new.note is distinct from old.note then
    select id into last_note
    from public.lead_events
    where lead_id = new.id
      and event_type = 'note_changed'
      and actor_id is not distinct from v_actor
      and created_at > now() - interval '10 minutes'
    order by created_at desc
    limit 1;

    if last_note is not null then
      update public.lead_events
      set to_value = left(new.note, 2000), created_at = now(), device = coalesce(v_device, device)
      where id = last_note;
    else
      insert into public.lead_events (lead_id, agent_id, actor_id, event_type, to_value, source, device)
      values (new.id, new.agent_id, v_actor, 'note_changed', left(new.note, 2000), v_source, v_device);
    end if;
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.refresh_overview_daily(p_agent_id uuid DEFAULT NULL::uuid)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  -- Delete existing auto-computed rows (keep rows with manual spend)
  DELETE FROM overview_daily
  WHERE (p_agent_id IS NULL OR agent_id = p_agent_id);

  -- Insert computed rows from leads
  INSERT INTO overview_daily (agent_id, date, spend, leads, leads_reached, appts, appts_held, mandates, commission_expected, commission_earned)
  SELECT
    l.agent_id,
    (l.created_at AT TIME ZONE 'Africa/Johannesburg')::date AS dt,
    0 AS spend,
    COUNT(*) AS leads,
    COUNT(*) FILTER (WHERE l.stage NOT IN ('New Lead', 'Invalid Number')) AS leads_reached,
    COUNT(*) FILTER (WHERE l.stage IN ('Booked', 'Mandate Signed')) AS appts,
    COUNT(*) FILTER (WHERE l.stage IN ('Mandate Signed')) AS appts_held,
    COUNT(*) FILTER (WHERE l.stage = 'Mandate Signed') AS mandates,
    COALESCE(SUM(l.commission) FILTER (WHERE l.stage = 'Mandate Signed'), 0) AS commission_expected,
    COALESCE(SUM(l.commission) FILTER (WHERE l.stage = 'Mandate Signed'), 0) AS commission_earned
  FROM leads l
  WHERE (p_agent_id IS NULL OR l.agent_id = p_agent_id)
  GROUP BY l.agent_id, dt
  ORDER BY dt;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.seed_setup_steps()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.setup_steps (agent_id, key, title, sort_order, done, cta_label, cta_url, cta_filled) values
    (new.id, 'signed_up',   'You''re signed up',       1, true,  null,          null,                               false),
    (new.id, 'setup_call',  'Setup call booked',        2, false, 'Book',       'https://cal.com',                  false),
    (new.id, 'connect_fb',  'Connect your Facebook',    3, false, 'Connect',    'https://business.facebook.com',    true),
    (new.id, 'go_live',     'Go live on your call',     4, false, 'View',       'https://business.facebook.com/adsmanager', false);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;


-- ==========================================================================
-- 10. Function privileges
-- ==========================================================================

revoke all on function dedupe_lead_call() from public, anon, authenticated, service_role; grant execute on function dedupe_lead_call() to postgres; grant execute on function dedupe_lead_call() to service_role;

revoke all on function enqueue_automations() from public, anon, authenticated, service_role; grant execute on function enqueue_automations() to postgres; grant execute on function enqueue_automations() to service_role;

revoke all on function find_user_id_by_phone(text) from public, anon, authenticated, service_role; grant execute on function find_user_id_by_phone(text) to postgres; grant execute on function find_user_id_by_phone(text) to service_role;

revoke all on function get_secret(text) from public, anon, authenticated, service_role; grant execute on function get_secret(text) to postgres; grant execute on function get_secret(text) to service_role;

revoke all on function is_operator() from public, anon, authenticated, service_role; grant execute on function is_operator() to postgres; grant execute on function is_operator() to authenticated; grant execute on function is_operator() to service_role; grant execute on function is_operator() to anon;

revoke all on function lead_page_funnel(uuid,timestamp with time zone) from public, anon, authenticated, service_role; grant execute on function lead_page_funnel(uuid,timestamp with time zone) to public; grant execute on function lead_page_funnel(uuid,timestamp with time zone) to postgres; grant execute on function lead_page_funnel(uuid,timestamp with time zone) to anon; grant execute on function lead_page_funnel(uuid,timestamp with time zone) to authenticated; grant execute on function lead_page_funnel(uuid,timestamp with time zone) to service_role;

revoke all on function record_lead_event() from public, anon, authenticated, service_role; grant execute on function record_lead_event() to postgres; grant execute on function record_lead_event() to service_role;

revoke all on function refresh_overview_daily(uuid) from public, anon, authenticated, service_role; grant execute on function refresh_overview_daily(uuid) to public; grant execute on function refresh_overview_daily(uuid) to postgres; grant execute on function refresh_overview_daily(uuid) to anon; grant execute on function refresh_overview_daily(uuid) to authenticated; grant execute on function refresh_overview_daily(uuid) to service_role;

revoke all on function seed_setup_steps() from public, anon, authenticated, service_role; grant execute on function seed_setup_steps() to postgres; grant execute on function seed_setup_steps() to service_role;

revoke all on function set_updated_at() from public, anon, authenticated, service_role; grant execute on function set_updated_at() to public; grant execute on function set_updated_at() to postgres; grant execute on function set_updated_at() to anon; grant execute on function set_updated_at() to authenticated; grant execute on function set_updated_at() to service_role;


-- ==========================================================================
-- 11. Triggers
-- ==========================================================================

CREATE TRIGGER agent_profiles_set_updated_at BEFORE UPDATE ON public.agent_profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER on_auth_user_created_seed_steps AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION seed_setup_steps();

CREATE TRIGGER fb_capi_config_set_updated_at BEFORE UPDATE ON public.fb_capi_config FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER lead_events_dedupe_call BEFORE INSERT ON public.lead_events FOR EACH ROW EXECUTE FUNCTION dedupe_lead_call();

CREATE TRIGGER leads_enqueue_automations AFTER INSERT OR UPDATE ON public.leads FOR EACH ROW EXECUTE FUNCTION enqueue_automations();

CREATE TRIGGER leads_record_event AFTER INSERT OR UPDATE ON public.leads FOR EACH ROW EXECUTE FUNCTION record_lead_event();

CREATE TRIGGER leads_set_updated_at BEFORE UPDATE ON public.leads FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ==========================================================================
-- 12. Row level security
-- ==========================================================================

alter table public.agent_daily_nudges enable row level security;

alter table public.agent_profiles enable row level security;

alter table public.automation_runs enable row level security;

alter table public.automation_steps enable row level security;

alter table public.automations enable row level security;

alter table public.call_questions enable row level security;

alter table public.custom_questions enable row level security;

alter table public.fb_api_state enable row level security;

alter table public.fb_capi_config enable row level security;

alter table public.fb_capi_events enable row level security;

alter table public.fb_form_cache enable row level security;

alter table public.fb_page_tokens enable row level security;

alter table public.lead_events enable row level security;

alter table public.lead_page_events enable row level security;

alter table public.lead_pages enable row level security;

alter table public.lead_share_tokens enable row level security;

alter table public.leads enable row level security;

alter table public.otp_codes enable row level security;

alter table public.overview_daily enable row level security;

alter table public.phone_otp_codes enable row level security;

alter table public.pipelines enable row level security;

alter table public.setup_steps enable row level security;

alter table public.sold_listings enable row level security;

alter table public.support_tickets enable row level security;


-- ==========================================================================
-- 13. Policies (public + storage)
-- ==========================================================================

create policy "Operators read daily nudges" on public.agent_daily_nudges as permissive for select to public using (is_operator());

create policy "Anon can read agent profiles for token leads" on public.agent_profiles as permissive for select to anon using ((agent_id IN ( SELECT lead_share_tokens.agent_id
   FROM lead_share_tokens
  WHERE (lead_share_tokens.expires_at > now()))));

create policy "Operators insert any profile" on public.agent_profiles as permissive for insert to public with check (is_operator());

create policy "Operators see all profiles" on public.agent_profiles as permissive for select to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators update any profile" on public.agent_profiles as permissive for update to public using (is_operator()) with check (is_operator());

create policy "agent selects own profile" on public.agent_profiles as permissive for select to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent updates own profile" on public.agent_profiles as permissive for update to public using ((agent_id = ( SELECT auth.uid() AS uid))) with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent upserts own profile" on public.agent_profiles as permissive for insert to public with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "operator updates automation_runs" on public.automation_runs as permissive for update to public using (is_operator()) with check (is_operator());

create policy "operator views automation_runs" on public.automation_runs as permissive for select to public using (is_operator());

create policy "operator manages automation_steps" on public.automation_steps as permissive for all to public using (is_operator()) with check (is_operator());

create policy "operator manages automations" on public.automations as permissive for all to public using (is_operator()) with check (is_operator());

create policy "agent inserts own questions" on public.call_questions as permissive for insert to public with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent selects own questions" on public.call_questions as permissive for select to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "Agents see own custom_questions" on public.custom_questions as permissive for all to public using ((agent_id = auth.uid()));

create policy "Anyone can read questions for public pages" on public.custom_questions as permissive for select to public using (true);

create policy "Operators delete all custom_questions" on public.custom_questions as permissive for delete to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators insert all custom_questions" on public.custom_questions as permissive for insert to public with check (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators see all custom_questions" on public.custom_questions as permissive for select to public using (true);

create policy "Operators update all custom_questions" on public.custom_questions as permissive for update to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Signed-in users read fb api state" on public.fb_api_state as permissive for select to authenticated using (true);

create policy "Operators read capi config" on public.fb_capi_config as permissive for select to public using (is_operator());

create policy "Operators write capi config" on public.fb_capi_config as permissive for all to public using (is_operator()) with check (is_operator());

create policy "Operators read capi events" on public.fb_capi_events as permissive for select to public using (is_operator());

create policy "Signed-in users read cached forms" on public.fb_form_cache as permissive for select to authenticated using (true);

create policy "Operators read lead history" on public.lead_events as permissive for select to public using (is_operator());

create policy "Signed-in users log calls on their leads" on public.lead_events as permissive for insert to public with check (((event_type = 'call'::text) AND (actor_id = auth.uid()) AND (is_operator() OR (EXISTS ( SELECT 1
   FROM leads l
  WHERE ((l.id = lead_events.lead_id) AND (l.agent_id = auth.uid())))))));

create policy "Operators read page funnel events" on public.lead_page_events as permissive for select to public using (is_operator());

create policy "Agents see own lead_pages" on public.lead_pages as permissive for all to public using ((agent_id = auth.uid()));

create policy "Anyone can read lead_pages publicly" on public.lead_pages as permissive for select to public using (true);

create policy "Operators delete all lead_pages" on public.lead_pages as permissive for delete to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators insert all lead_pages" on public.lead_pages as permissive for insert to public with check (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators see all lead_pages" on public.lead_pages as permissive for select to public using (true);

create policy "Operators update all lead_pages" on public.lead_pages as permissive for update to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Agents manage own tokens" on public.lead_share_tokens as permissive for all to public using ((agent_id = auth.uid()));

create policy "Anyone can read lead_share_tokens" on public.lead_share_tokens as permissive for select to public using (true);

create policy "Anon can read leads with valid tokens" on public.leads as permissive for select to anon using ((id IN ( SELECT lead_share_tokens.lead_id
   FROM lead_share_tokens
  WHERE (lead_share_tokens.expires_at > now()))));

create policy "Authenticated can read leads with valid tokens" on public.leads as permissive for select to authenticated using ((id IN ( SELECT lead_share_tokens.lead_id
   FROM lead_share_tokens
  WHERE (lead_share_tokens.expires_at > now()))));

create policy "Operators delete all leads" on public.leads as permissive for delete to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators see all leads" on public.leads as permissive for select to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators update all leads" on public.leads as permissive for update to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Public can insert leads" on public.leads as permissive for insert to public with check (true);

create policy "agent deletes own leads" on public.leads as permissive for delete to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent inserts own leads" on public.leads as permissive for insert to public with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent selects own leads" on public.leads as permissive for select to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent updates own leads" on public.leads as permissive for update to public using ((agent_id = ( SELECT auth.uid() AS uid))) with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "Operators see all overview" on public.overview_daily as permissive for select to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "agent selects own overview" on public.overview_daily as permissive for select to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "Agents see own pipelines" on public.pipelines as permissive for all to public using ((agent_id = auth.uid()));

create policy "Anyone can read pipelines publicly" on public.pipelines as permissive for select to public using (true);

create policy "Operators delete all pipelines" on public.pipelines as permissive for delete to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators insert all pipelines" on public.pipelines as permissive for insert to public with check (((agent_id = auth.uid()) OR is_operator()));

create policy "Operators see all pipelines" on public.pipelines as permissive for select to public using (true);

create policy "Operators update all pipelines" on public.pipelines as permissive for update to public using (((agent_id = auth.uid()) OR is_operator()));

create policy "agent selects own steps" on public.setup_steps as permissive for select to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent updates own steps" on public.setup_steps as permissive for update to public using ((agent_id = ( SELECT auth.uid() AS uid))) with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "Anyone can read sold_listings" on public.sold_listings as permissive for select to public using (true);

create policy "Operators delete sold_listings" on public.sold_listings as permissive for delete to public using (is_operator());

create policy "Operators insert sold_listings" on public.sold_listings as permissive for insert to public with check (is_operator());

create policy "Operators update sold_listings" on public.sold_listings as permissive for update to public using (is_operator());

create policy "agent inserts own tickets" on public.support_tickets as permissive for insert to public with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent selects own tickets" on public.support_tickets as permissive for select to public using ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "agent updates own tickets" on public.support_tickets as permissive for update to public using ((agent_id = ( SELECT auth.uid() AS uid))) with check ((agent_id = ( SELECT auth.uid() AS uid)));

create policy "Anyone can read logos" on storage.objects as permissive for select to public using ((bucket_id = 'logos'::text));

create policy "Auth users update logos" on storage.objects as permissive for update to public using (((bucket_id = 'logos'::text) AND (auth.role() = 'authenticated'::text)));

create policy "Auth users upload logos" on storage.objects as permissive for insert to public with check (((bucket_id = 'logos'::text) AND (auth.role() = 'authenticated'::text)));


-- ==========================================================================
-- 14. Table privileges (anon / authenticated)
-- ==========================================================================

revoke all on table public.agent_daily_nudges from anon, authenticated; grant delete on table public.agent_daily_nudges to anon; grant delete on table public.agent_daily_nudges to authenticated; grant insert on table public.agent_daily_nudges to anon; grant insert on table public.agent_daily_nudges to authenticated; grant maintain on table public.agent_daily_nudges to authenticated; grant maintain on table public.agent_daily_nudges to anon; grant references on table public.agent_daily_nudges to authenticated; grant references on table public.agent_daily_nudges to anon; grant select on table public.agent_daily_nudges to authenticated; grant select on table public.agent_daily_nudges to anon; grant trigger on table public.agent_daily_nudges to anon; grant trigger on table public.agent_daily_nudges to authenticated; grant truncate on table public.agent_daily_nudges to anon; grant truncate on table public.agent_daily_nudges to authenticated; grant update on table public.agent_daily_nudges to anon; grant update on table public.agent_daily_nudges to authenticated;

revoke all on table public.agent_profiles from anon, authenticated; grant delete on table public.agent_profiles to anon; grant delete on table public.agent_profiles to authenticated; grant insert on table public.agent_profiles to anon; grant insert on table public.agent_profiles to authenticated; grant maintain on table public.agent_profiles to authenticated; grant maintain on table public.agent_profiles to anon; grant references on table public.agent_profiles to authenticated; grant references on table public.agent_profiles to anon; grant select on table public.agent_profiles to authenticated; grant select on table public.agent_profiles to anon; grant trigger on table public.agent_profiles to anon; grant trigger on table public.agent_profiles to authenticated; grant truncate on table public.agent_profiles to anon; grant truncate on table public.agent_profiles to authenticated; grant update on table public.agent_profiles to anon; grant update on table public.agent_profiles to authenticated;

revoke all on table public.automation_runs from anon, authenticated; grant delete on table public.automation_runs to anon; grant delete on table public.automation_runs to authenticated; grant insert on table public.automation_runs to anon; grant insert on table public.automation_runs to authenticated; grant maintain on table public.automation_runs to authenticated; grant maintain on table public.automation_runs to anon; grant references on table public.automation_runs to authenticated; grant references on table public.automation_runs to anon; grant select on table public.automation_runs to authenticated; grant select on table public.automation_runs to anon; grant trigger on table public.automation_runs to anon; grant trigger on table public.automation_runs to authenticated; grant truncate on table public.automation_runs to anon; grant truncate on table public.automation_runs to authenticated; grant update on table public.automation_runs to anon; grant update on table public.automation_runs to authenticated;

revoke all on table public.automation_steps from anon, authenticated; grant delete on table public.automation_steps to anon; grant delete on table public.automation_steps to authenticated; grant insert on table public.automation_steps to anon; grant insert on table public.automation_steps to authenticated; grant maintain on table public.automation_steps to authenticated; grant maintain on table public.automation_steps to anon; grant references on table public.automation_steps to authenticated; grant references on table public.automation_steps to anon; grant select on table public.automation_steps to authenticated; grant select on table public.automation_steps to anon; grant trigger on table public.automation_steps to anon; grant trigger on table public.automation_steps to authenticated; grant truncate on table public.automation_steps to anon; grant truncate on table public.automation_steps to authenticated; grant update on table public.automation_steps to anon; grant update on table public.automation_steps to authenticated;

revoke all on table public.automations from anon, authenticated; grant delete on table public.automations to anon; grant delete on table public.automations to authenticated; grant insert on table public.automations to anon; grant insert on table public.automations to authenticated; grant maintain on table public.automations to authenticated; grant maintain on table public.automations to anon; grant references on table public.automations to authenticated; grant references on table public.automations to anon; grant select on table public.automations to authenticated; grant select on table public.automations to anon; grant trigger on table public.automations to anon; grant trigger on table public.automations to authenticated; grant truncate on table public.automations to anon; grant truncate on table public.automations to authenticated; grant update on table public.automations to anon; grant update on table public.automations to authenticated;

revoke all on table public.call_questions from anon, authenticated; grant delete on table public.call_questions to anon; grant delete on table public.call_questions to authenticated; grant insert on table public.call_questions to anon; grant insert on table public.call_questions to authenticated; grant maintain on table public.call_questions to authenticated; grant maintain on table public.call_questions to anon; grant references on table public.call_questions to authenticated; grant references on table public.call_questions to anon; grant select on table public.call_questions to authenticated; grant select on table public.call_questions to anon; grant trigger on table public.call_questions to anon; grant trigger on table public.call_questions to authenticated; grant truncate on table public.call_questions to anon; grant truncate on table public.call_questions to authenticated; grant update on table public.call_questions to anon; grant update on table public.call_questions to authenticated;

revoke all on table public.custom_questions from anon, authenticated; grant delete on table public.custom_questions to anon; grant delete on table public.custom_questions to authenticated; grant insert on table public.custom_questions to anon; grant insert on table public.custom_questions to authenticated; grant maintain on table public.custom_questions to authenticated; grant maintain on table public.custom_questions to anon; grant references on table public.custom_questions to authenticated; grant references on table public.custom_questions to anon; grant select on table public.custom_questions to authenticated; grant select on table public.custom_questions to anon; grant trigger on table public.custom_questions to anon; grant trigger on table public.custom_questions to authenticated; grant truncate on table public.custom_questions to anon; grant truncate on table public.custom_questions to authenticated; grant update on table public.custom_questions to anon; grant update on table public.custom_questions to authenticated;

revoke all on table public.fb_api_state from anon, authenticated; grant delete on table public.fb_api_state to anon; grant delete on table public.fb_api_state to authenticated; grant insert on table public.fb_api_state to anon; grant insert on table public.fb_api_state to authenticated; grant maintain on table public.fb_api_state to authenticated; grant maintain on table public.fb_api_state to anon; grant references on table public.fb_api_state to authenticated; grant references on table public.fb_api_state to anon; grant select on table public.fb_api_state to authenticated; grant select on table public.fb_api_state to anon; grant trigger on table public.fb_api_state to anon; grant trigger on table public.fb_api_state to authenticated; grant truncate on table public.fb_api_state to anon; grant truncate on table public.fb_api_state to authenticated; grant update on table public.fb_api_state to anon; grant update on table public.fb_api_state to authenticated;

revoke all on table public.fb_capi_config from anon, authenticated; grant delete on table public.fb_capi_config to anon; grant delete on table public.fb_capi_config to authenticated; grant insert on table public.fb_capi_config to anon; grant insert on table public.fb_capi_config to authenticated; grant maintain on table public.fb_capi_config to authenticated; grant maintain on table public.fb_capi_config to anon; grant references on table public.fb_capi_config to authenticated; grant references on table public.fb_capi_config to anon; grant select on table public.fb_capi_config to authenticated; grant select on table public.fb_capi_config to anon; grant trigger on table public.fb_capi_config to anon; grant trigger on table public.fb_capi_config to authenticated; grant truncate on table public.fb_capi_config to anon; grant truncate on table public.fb_capi_config to authenticated; grant update on table public.fb_capi_config to anon; grant update on table public.fb_capi_config to authenticated;

revoke all on table public.fb_capi_events from anon, authenticated; grant delete on table public.fb_capi_events to anon; grant delete on table public.fb_capi_events to authenticated; grant insert on table public.fb_capi_events to anon; grant insert on table public.fb_capi_events to authenticated; grant maintain on table public.fb_capi_events to authenticated; grant maintain on table public.fb_capi_events to anon; grant references on table public.fb_capi_events to authenticated; grant references on table public.fb_capi_events to anon; grant select on table public.fb_capi_events to authenticated; grant select on table public.fb_capi_events to anon; grant trigger on table public.fb_capi_events to anon; grant trigger on table public.fb_capi_events to authenticated; grant truncate on table public.fb_capi_events to anon; grant truncate on table public.fb_capi_events to authenticated; grant update on table public.fb_capi_events to anon; grant update on table public.fb_capi_events to authenticated;

revoke all on table public.fb_form_cache from anon, authenticated; grant delete on table public.fb_form_cache to anon; grant delete on table public.fb_form_cache to authenticated; grant insert on table public.fb_form_cache to anon; grant insert on table public.fb_form_cache to authenticated; grant maintain on table public.fb_form_cache to authenticated; grant maintain on table public.fb_form_cache to anon; grant references on table public.fb_form_cache to authenticated; grant references on table public.fb_form_cache to anon; grant select on table public.fb_form_cache to authenticated; grant select on table public.fb_form_cache to anon; grant trigger on table public.fb_form_cache to anon; grant trigger on table public.fb_form_cache to authenticated; grant truncate on table public.fb_form_cache to anon; grant truncate on table public.fb_form_cache to authenticated; grant update on table public.fb_form_cache to anon; grant update on table public.fb_form_cache to authenticated;

revoke all on table public.fb_page_tokens from anon, authenticated; grant delete on table public.fb_page_tokens to anon; grant delete on table public.fb_page_tokens to authenticated; grant insert on table public.fb_page_tokens to anon; grant insert on table public.fb_page_tokens to authenticated; grant maintain on table public.fb_page_tokens to authenticated; grant maintain on table public.fb_page_tokens to anon; grant references on table public.fb_page_tokens to authenticated; grant references on table public.fb_page_tokens to anon; grant select on table public.fb_page_tokens to authenticated; grant select on table public.fb_page_tokens to anon; grant trigger on table public.fb_page_tokens to anon; grant trigger on table public.fb_page_tokens to authenticated; grant truncate on table public.fb_page_tokens to anon; grant truncate on table public.fb_page_tokens to authenticated; grant update on table public.fb_page_tokens to anon; grant update on table public.fb_page_tokens to authenticated;

revoke all on table public.lead_events from anon, authenticated; grant delete on table public.lead_events to anon; grant delete on table public.lead_events to authenticated; grant insert on table public.lead_events to anon; grant insert on table public.lead_events to authenticated; grant maintain on table public.lead_events to authenticated; grant maintain on table public.lead_events to anon; grant references on table public.lead_events to authenticated; grant references on table public.lead_events to anon; grant select on table public.lead_events to authenticated; grant select on table public.lead_events to anon; grant trigger on table public.lead_events to anon; grant trigger on table public.lead_events to authenticated; grant truncate on table public.lead_events to anon; grant truncate on table public.lead_events to authenticated; grant update on table public.lead_events to anon; grant update on table public.lead_events to authenticated;

revoke all on table public.lead_page_events from anon, authenticated; grant delete on table public.lead_page_events to anon; grant delete on table public.lead_page_events to authenticated; grant insert on table public.lead_page_events to anon; grant insert on table public.lead_page_events to authenticated; grant maintain on table public.lead_page_events to authenticated; grant maintain on table public.lead_page_events to anon; grant references on table public.lead_page_events to authenticated; grant references on table public.lead_page_events to anon; grant select on table public.lead_page_events to authenticated; grant select on table public.lead_page_events to anon; grant trigger on table public.lead_page_events to anon; grant trigger on table public.lead_page_events to authenticated; grant truncate on table public.lead_page_events to anon; grant truncate on table public.lead_page_events to authenticated; grant update on table public.lead_page_events to anon; grant update on table public.lead_page_events to authenticated;

revoke all on table public.lead_pages from anon, authenticated; grant delete on table public.lead_pages to anon; grant delete on table public.lead_pages to authenticated; grant insert on table public.lead_pages to anon; grant insert on table public.lead_pages to authenticated; grant maintain on table public.lead_pages to authenticated; grant maintain on table public.lead_pages to anon; grant references on table public.lead_pages to authenticated; grant references on table public.lead_pages to anon; grant select on table public.lead_pages to authenticated; grant select on table public.lead_pages to anon; grant trigger on table public.lead_pages to anon; grant trigger on table public.lead_pages to authenticated; grant truncate on table public.lead_pages to anon; grant truncate on table public.lead_pages to authenticated; grant update on table public.lead_pages to anon; grant update on table public.lead_pages to authenticated;

revoke all on table public.lead_share_tokens from anon, authenticated; grant delete on table public.lead_share_tokens to anon; grant delete on table public.lead_share_tokens to authenticated; grant insert on table public.lead_share_tokens to anon; grant insert on table public.lead_share_tokens to authenticated; grant maintain on table public.lead_share_tokens to authenticated; grant maintain on table public.lead_share_tokens to anon; grant references on table public.lead_share_tokens to authenticated; grant references on table public.lead_share_tokens to anon; grant select on table public.lead_share_tokens to authenticated; grant select on table public.lead_share_tokens to anon; grant trigger on table public.lead_share_tokens to anon; grant trigger on table public.lead_share_tokens to authenticated; grant truncate on table public.lead_share_tokens to anon; grant truncate on table public.lead_share_tokens to authenticated; grant update on table public.lead_share_tokens to anon; grant update on table public.lead_share_tokens to authenticated;

revoke all on table public.leads from anon, authenticated; grant delete on table public.leads to anon; grant delete on table public.leads to authenticated; grant insert on table public.leads to anon; grant insert on table public.leads to authenticated; grant maintain on table public.leads to authenticated; grant maintain on table public.leads to anon; grant references on table public.leads to authenticated; grant references on table public.leads to anon; grant select on table public.leads to authenticated; grant select on table public.leads to anon; grant trigger on table public.leads to anon; grant trigger on table public.leads to authenticated; grant truncate on table public.leads to anon; grant truncate on table public.leads to authenticated; grant update on table public.leads to anon; grant update on table public.leads to authenticated;

revoke all on table public.otp_codes from anon, authenticated; grant delete on table public.otp_codes to anon; grant delete on table public.otp_codes to authenticated; grant insert on table public.otp_codes to anon; grant insert on table public.otp_codes to authenticated; grant maintain on table public.otp_codes to authenticated; grant maintain on table public.otp_codes to anon; grant references on table public.otp_codes to authenticated; grant references on table public.otp_codes to anon; grant select on table public.otp_codes to authenticated; grant select on table public.otp_codes to anon; grant trigger on table public.otp_codes to anon; grant trigger on table public.otp_codes to authenticated; grant truncate on table public.otp_codes to anon; grant truncate on table public.otp_codes to authenticated; grant update on table public.otp_codes to anon; grant update on table public.otp_codes to authenticated;

revoke all on table public.overview_daily from anon, authenticated; grant delete on table public.overview_daily to anon; grant delete on table public.overview_daily to authenticated; grant insert on table public.overview_daily to anon; grant insert on table public.overview_daily to authenticated; grant maintain on table public.overview_daily to authenticated; grant maintain on table public.overview_daily to anon; grant references on table public.overview_daily to authenticated; grant references on table public.overview_daily to anon; grant select on table public.overview_daily to authenticated; grant select on table public.overview_daily to anon; grant trigger on table public.overview_daily to anon; grant trigger on table public.overview_daily to authenticated; grant truncate on table public.overview_daily to anon; grant truncate on table public.overview_daily to authenticated; grant update on table public.overview_daily to anon; grant update on table public.overview_daily to authenticated;

revoke all on table public.phone_otp_codes from anon, authenticated; grant delete on table public.phone_otp_codes to anon; grant delete on table public.phone_otp_codes to authenticated; grant insert on table public.phone_otp_codes to anon; grant insert on table public.phone_otp_codes to authenticated; grant maintain on table public.phone_otp_codes to authenticated; grant maintain on table public.phone_otp_codes to anon; grant references on table public.phone_otp_codes to authenticated; grant references on table public.phone_otp_codes to anon; grant select on table public.phone_otp_codes to authenticated; grant select on table public.phone_otp_codes to anon; grant trigger on table public.phone_otp_codes to anon; grant trigger on table public.phone_otp_codes to authenticated; grant truncate on table public.phone_otp_codes to anon; grant truncate on table public.phone_otp_codes to authenticated; grant update on table public.phone_otp_codes to anon; grant update on table public.phone_otp_codes to authenticated;

revoke all on table public.pipelines from anon, authenticated; grant delete on table public.pipelines to anon; grant delete on table public.pipelines to authenticated; grant insert on table public.pipelines to anon; grant insert on table public.pipelines to authenticated; grant maintain on table public.pipelines to authenticated; grant maintain on table public.pipelines to anon; grant references on table public.pipelines to authenticated; grant references on table public.pipelines to anon; grant select on table public.pipelines to authenticated; grant select on table public.pipelines to anon; grant trigger on table public.pipelines to anon; grant trigger on table public.pipelines to authenticated; grant truncate on table public.pipelines to anon; grant truncate on table public.pipelines to authenticated; grant update on table public.pipelines to anon; grant update on table public.pipelines to authenticated;

revoke all on table public.setup_steps from anon, authenticated; grant delete on table public.setup_steps to anon; grant delete on table public.setup_steps to authenticated; grant insert on table public.setup_steps to anon; grant insert on table public.setup_steps to authenticated; grant maintain on table public.setup_steps to authenticated; grant maintain on table public.setup_steps to anon; grant references on table public.setup_steps to authenticated; grant references on table public.setup_steps to anon; grant select on table public.setup_steps to authenticated; grant select on table public.setup_steps to anon; grant trigger on table public.setup_steps to anon; grant trigger on table public.setup_steps to authenticated; grant truncate on table public.setup_steps to anon; grant truncate on table public.setup_steps to authenticated; grant update on table public.setup_steps to anon; grant update on table public.setup_steps to authenticated;

revoke all on table public.sold_listings from anon, authenticated; grant delete on table public.sold_listings to anon; grant delete on table public.sold_listings to authenticated; grant insert on table public.sold_listings to anon; grant insert on table public.sold_listings to authenticated; grant maintain on table public.sold_listings to authenticated; grant maintain on table public.sold_listings to anon; grant references on table public.sold_listings to authenticated; grant references on table public.sold_listings to anon; grant select on table public.sold_listings to authenticated; grant select on table public.sold_listings to anon; grant trigger on table public.sold_listings to anon; grant trigger on table public.sold_listings to authenticated; grant truncate on table public.sold_listings to anon; grant truncate on table public.sold_listings to authenticated; grant update on table public.sold_listings to anon; grant update on table public.sold_listings to authenticated;

revoke all on table public.support_tickets from anon, authenticated; grant delete on table public.support_tickets to anon; grant delete on table public.support_tickets to authenticated; grant insert on table public.support_tickets to anon; grant insert on table public.support_tickets to authenticated; grant maintain on table public.support_tickets to authenticated; grant maintain on table public.support_tickets to anon; grant references on table public.support_tickets to authenticated; grant references on table public.support_tickets to anon; grant select on table public.support_tickets to authenticated; grant select on table public.support_tickets to anon; grant trigger on table public.support_tickets to anon; grant trigger on table public.support_tickets to authenticated; grant truncate on table public.support_tickets to anon; grant truncate on table public.support_tickets to authenticated; grant update on table public.support_tickets to anon; grant update on table public.support_tickets to authenticated;


-- ==========================================================================
-- 15. Storage buckets
-- ==========================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('logos', 'logos', t, null, null) on conflict (id) do nothing;


-- ==========================================================================
-- 16. Cron jobs
-- ==========================================================================

select cron.schedule('daily-stage-nudge-weekdays', '0 14 * * 1-5', '
  select net.http_post(
    url := ''https://yfcnsvrhojpysrzqrkdi.supabase.co/functions/v1/daily-stage-nudge'',
    headers := ''{"Content-Type": "application/json"}''::jsonb,
    body := ''{}''::jsonb
  );
  '); select cron.alter_job(job_id := (select jobid from cron.job where jobname = 'daily-stage-nudge-weekdays'), active := false);

select cron.schedule('run-automations-every-minute', '* * * * *', '
  select net.http_post(
    url := ''https://yfcnsvrhojpysrzqrkdi.supabase.co/functions/v1/run-automations'',
    headers := ''{"Content-Type": "application/json"}''::jsonb,
    body := ''{}''::jsonb
  );
  ');

select cron.schedule('sync-fb-leads-every-5-min', '*/15 * * * *', '
  select net.http_post(
    url := ''https://yfcnsvrhojpysrzqrkdi.supabase.co/functions/v1/sync-fb-leads'',
    headers := ''{"Content-Type": "application/json"}''::jsonb,
    body := ''{"sinceDays": 3, "includePageForms": true}''::jsonb
  );
  ');


-- ==========================================================================
-- 17. Comments
-- ==========================================================================

comment on column public.agent_profiles.avatar_url is 'The agent''s face. sidebar_logo_url stays the agency/brand mark.';

comment on column public.custom_questions.low_quality_answers is 'Answers that still create a lead but are not reported to Facebook as a conversion. Distinct from disqualify_answers, which creates no lead at all.';

comment on column public.lead_pages.fb_page_id is 'The Facebook page this source''s form lives on. Null means "the agent''s own page" (agent_profiles.fb_page_id), which is correct for almost every source.';

comment on column public.leads.attribution is 'Ad/traffic attribution captured on the landing page at first visit: utm_*, fbclid, ad_id, campaign_id, referrer. Empty for leads with no captured source.';

comment on column public.leads.commission_received_at is 'When the commission was actually banked. Null = still only expected. Only leads with this set count toward earned commission on the Overview.';

